# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='hex',
            new_name='hexadecimal',
        ),
        migrations.AddField(
            model_name='colors',
            name='blue',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='colors',
            name='green',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='colors',
            name='red',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
